name: PlatformIO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run native unit tests
      run: platformio test -e native

    - name: Build for Arduino Uno
      run: platformio run -e uno

    - name: Build for ESP32 DevKit
      run: platformio run -e esp32dev

    - name: Build for Raspberry Pi Pico
      run: platformio run -e pico
